name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 6 * * *"   # Her gün 06:00 UTC
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven

      - name: Build and Run Scraper
        run: mvn clean compile exec:java

      - name: Upload public directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-html
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: scraper

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download public directory artifact
        uses: actions/download-artifact@v4
        with:
          name: public-html
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
