name: Build and Deploy to Netlify

on:
  schedule:
    - cron: "0 6 * * *"  # Her gün 06:00 UTC’de çalışır
  workflow_dispatch:      # İster manuel tetikleme için

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # Java ve Maven kur
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # ChromeDriver kurulumu (WebDriverManager ile de çalışabilir)
      - name: Install dependencies
        run: mvn dependency:resolve

      # Java Scraper çalıştır
      - name: Run Scraper
        run: mvn clean compile exec:java -Dexec.mainClass="com.example.Scraper"

      # Netlify deploy
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ./public
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
